console_title_template = "{{ .Shell }} in {{ .Folder }}"
version = 3
final_space = true

[palette]
  aqua = "#91ddff"
  black = "#100e23"
  blue = "#015875"
  gray = "#c5b6ad"
  green = "#429e42"
  magenta = "#c236ae"
  orange = "#ff9248"
  red = "#f26d50"
  white = "#eeeeee"
  yellow = "#d5de76"

[transient_prompt]
  template = "❯ "
  background = "transparent"
  foreground_templates = ["{{if gt .Code 0}}p:red{{else}}p:magenta{{end}}"]

[secondary_prompt]
  template = "❯❯ "
  background = "transparent"
  foreground = "p:magenta"

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "text"
    template = "{{ if .Env.SSH_CONNECTION }} {{ .HostName }} {{ end }}"
    background = "p:blue"
    foreground = "p:white"

  [[blocks.segments]]
    type = "path"
    template = " {{ .Path }} "
    style = "powerline"
    background = "p:aqua"
    foreground = "p:black"

    [blocks.segments.properties]
      style = "full"

  [[blocks.segments]]
    style = "accordion"
    powerline_symbol = ""
    background = "p:blue"

  [[blocks.segments]]
    type = "git"
    template = " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} *{{ end }}"
    style = "powerline"
    powerline_symbol = ""
    background = "p:green"
    background_templates = [
      "{{ if or (.Working.Changed) (.Staging.Changed) }}p:orange{{ end }}",
      "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}",
      "{{ if gt .Ahead 0 }}p:yellow{{ end }}",
      "{{ if gt .Behind 0 }}p:gray{{ end }}",
    ]
    foreground = "p:black"

    [blocks.segments.properties]
      branch_ahead_icon = "↑"
      branch_behind_icon = "↓"
      branch_gone = "≢"
      branch_icon = "\ue709 "
      branch_identical_icon = "≡"
      cherry_pick_icon = "✓ "
      commit_icon = "▷ "
      fetch_stash_count = true
      fetch_status = true
      merge_icon = "◴ "
      no_commits_icon = "[no commits]"
      rebase_icon = "Ɫ "
      tag_icon = "▶ "

[[blocks]]
  type = "rprompt"
  overflow = "hidden"

  [[blocks.segments]]
    type = "executiontime"
    template = "{{ .FormattedMs }}"
    style = "plain"
    background = "transparent"
    foreground = "p:yellow"

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "text"
    template = "❯"
    background = "transparent"
    foreground_templates = ["{{if gt .Code 0}}p:red{{else}}p:magenta{{end}}"]
